apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world-helm-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: asajjan246/hello-world-app
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/image-tag-update-strategy: semver
    argocd-image-updater.argoproj.io/helm-values: image.tag
spec:
  project: default

  source:
    repoURL: https://github.com/asajjan1989/hello-world-helm.git
    targetRevision: HEAD
    path: helmcharts
    helm:
      valueFiles:
        - values-dev.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: demo-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true