apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world-helm-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/asajjan1989/hello-world-helm.git
    targetRevision: HEAD
    path: helmcharts
    helm:
      valueFiles:
        - values-dev.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: demo-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true